# Generated by Django 5.1.3 on 2025-01-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название подразделения')),
                ('division_id', models.IntegerField(unique=True, verbose_name='ID подразделения в системе Супервизор')),
                ('count_windows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество окон')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='supervisor__name_5e9d05_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='ФИО пользователя')),
                ('photo_base64', models.TextField(blank=True, null=True, verbose_name='Фото профиля в base64')),
                ('eo_database_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя в системе ЭО')),
                ('eo_database_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя в системе ЭО')),
                ('divisions', models.ManyToManyField(to='supervisor.division', verbose_name='Подразделения')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='supervisor__full_na_f6c41f_idx')],
            },
        ),
    ]
